spring:
  profiles: generatesql
  flyway.enabled: false
  jpa.properties.javax.persistence.schema-generation.scripts:
    action: create
    create-target: V1__initial_script.sql
    create-source: metadata
spring.datasource.url: xxxx
spring.datasource.username: xxxx
spring.datasource.password: xxxx
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
