version: '3.1'

services:
  app:
    container_name: xxxx
    image: bookaro:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: xxxx
      SPRING_DATASOURCE_USERNAME: xxxx
      SPRING_DATASOURCE_PASSWORD: xxxx
    ports:
      - 9080:8080
  db:
    container_name: bookarodb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: xxxx
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxx
    ports:
      - 7432:5432
